### ISSUE TITLE
Visualisations reset to default upon reloading / loading from URL

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1374] opened 2024-01-11 14:42 UTC
### What went wrong?

When navigating to any visualization via URL (i.e. also via reloading the page), it navigates to the default visualization, i.e. Number of Results compared by the default, usually Year or Date. 

### What did you expect to happen?

I expected to get the visualisation I put in the URL.

### Where did you find the bug?

- [X] https://ianalyzer.hum.uu.nl
- [X] https://peopleandparliament.hum.uu.nl
- [ ] https://peace.sites.uu.nl
- [ ] a server hosted elsewhere (i.e. not by the research software lab)
- [X] a local server

### Steps to reproduce

Go to any visualisation that isn't the default and hit reload.

**Comment by Meesch** [comment] 2024-01-11 15:11
After some discussion with @JeltevanBoheemen, I decided we will need to discuss a strategy to deal with this in the next meeting. It is also related to #1268, and possibly other issues as well.

**Comment by BeritJanssen** [comment] 2024-01-11 15:39
This is caused by multiple triggers of the `setStateFromParams` function. The current setup of the routing is not ideal.

**Comment by Meesch** [comment] 2024-01-12 09:56
Yes, we wanted to discuss the routing/params issue in the next meeting, deciding on a strategy to implement a single system

**Comment by BeritJanssen** [comment] 2024-01-18 10:30
We agreed that it would be better to move the handling of parameters to a dedicated model*, which has a subject as a source of truth of the application state, and can translate the route parameters into application state, and application state to parameters - comparable to the setup of the queryModel. 

*Angular documentation would argue to turn this into services, but since queryModel is now set up in models, it would probably be best to follow that decision for the other state management, too.

**Comment by BeritJanssen** [comment] 2024-01-19 08:17
Upon further thought, I think this particular bug is caused by the `VisualizationComponent` listening to the query parameters, and reiniting at the same time as its current child. So following up on a suggestion by @lukavdplas, I think the bug can be fixed by not using queryParams for the information the `VisualizationComponent` is supposed to handle. This comes down to removing `extends ParamDirective` from `VisualizationComponent`, and to handle the fact that we are in the visualization tab, and the type of visualization that is being shown, through the route. Everything else can remain pretty much unchanged - the `queryModel` comes in through an `@Input`, so upon initialization, a visualization leaf component would just check if there are any relevant parameters in the route, and set its state accordingly. I do think `VisualizationComponent` does not actually need information about the `queryModel`, so it might be more elegant to let the visualization leaf components listen to the `QueryModel.update$` Subject, rather than passing this information through.

**Comment by lukavdplas** [comment] 2024-02-09 11:45
Short update: I'm working on this as part of #1403, so I'm optimistic this will be fixed in the next release.

As Berit mentioned, I had suggested that the visualistion is more "navigation" than "query", and so routes like these might be more appropriate:

`ianalyzer.hum.uu.nl/corpus/troonredes/search?query="test"` to view search results

`ianalyzer.hum.uu.nl/corpus/troonredes/visualize/resultcount?query="test"&normalization="documents"` to view the "number of results" visualisation of the same query

That said, routes are an important part of reproducibility for I-analyzer, so we should be conservative with making breaking changes there. I think for now, it's better to fix the error with the routes we have.

**Comment by lukavdplas** [comment] 2024-03-05 11:18
closed by #1467

**Closed by lukavdplas** 2024-03-05 11:18 UTC
Labels: bug, frontend
