### ISSUE TITLE
Re-index the corpora for stemmed highlighting functionality

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1285] opened 2023-10-10 12:06 UTC
In order to optimally use the new highlighting functionality, the existing corpora need to be re-indexed. To ease the process of updating this, only a single change needs to be made to the corpus definition, i.e. the setting `updated_highlighting` needs to be set to `True` in the `main_content_mapping` method, see example below for the speech field in parliamentary corpora:

```python
        es_mapping = main_content_mapping(token_counts=True, stopword_analysis=True, stemming_analysis=True, updated_highlighting=True),
```

This needs to be updated for all corpora that we deem interesting/functional enough to have this functionality (and locally tested with a test set), pushed to acceptation/test/production, and then the corpus needs to be re-indexed. The progress on the corpora will be tracked here:

- [ ] Dutch Annual Reports
- [ ] Dutch Public Newspapers
- [ ] Dutch Newspapers (Delpher)
- [ ] Guardian-Observer
- [ ] DIOPTRA-L
- [ ] Periodicals
- [ ] Times
- [ ] Eighteenth Century Collections Online
- [ ] Judicial System Netherlands
- [ ] DBNL

**Comment by lukavdplas** [comment] 2023-10-10 13:11
Isn´t this a duplicate of #1281 ? If not, I would recommend against doing two re-indexing migrations simultaneously.

**Comment by Meesch** [comment] 2023-10-10 13:12
Uhmmm good question. @BeritJanssen ?

**Comment by BeritJanssen** [comment] 2023-10-11 09:29
Yes, duplicate!

**Closed by BeritJanssen** 2023-10-11 09:29 UTC

**Comment by BeritJanssen** [comment] 2023-10-11 09:31
@Meesch , as for the Dutchnewspapers (Delpher), I hope that the correct mapping is added now that it's being reindexed from source? I wasn't actually planning to do any reindex operation on this large corpus if we get a new version soon anyway.
